### ISSUE TITLE
Images in the portfolio section are misaligned

### ISSUE THREAD

**Issue by rperry99** [rperry99/portfolio-2020#24]

**Comment by rperry99** [comment]
Images should be centered within the card. 

Issue: 
![image](https://user-images.githubusercontent.com/24259120/92669940-e5c96a80-f2e0-11ea-8534-8b4dfeaec5e8.png)

**Comment by w3bdesign** [comment]
@rperry99 

See https://github.com/rperry99/portfolio-2020/pull/26

**Comment by rperry99** [comment]
Thank you @w3bdesign Looks to be fixed!
